# Generated by simit; edit the producer, then run `simit init ci`.
"""Signed-source native package artifacts, checksum conflicts, and propagation."""

import base64
import email.parser
import hashlib
import json
import os
from pathlib import Path
import re
import subprocess
import sys
import tarfile
import tempfile
import time
import tomllib
import urllib.error
import urllib.parse
import urllib.request
import zipfile


def require(condition, message):
    if not condition:
        raise RuntimeError(message)


def command(arguments, **kwargs):
    return subprocess.run(arguments, check=True, **kwargs)


def normalize(name):
    return re.sub(r"[-_.]+", "-", name).lower()


def python_version(version):
    # Static SemVer owners must also have a version accepted by public PyPI.
    match = re.fullmatch(r"(\d+\.\d+\.\d+)(?:-(alpha|beta|rc|dev)(?:\.(\d+))?)?", version)
    require(match is not None, "Python publication requires a PyPI-compatible SemVer version")
    base, label, number = match.groups()
    suffix = {"alpha": "a", "beta": "b", "rc": "rc", "dev": ".dev"}
    return base + (suffix[label] + (number or "0") if label else "")


def digest(path, algorithm="sha256"):
    with path.open("rb") as source:
        return hashlib.file_digest(source, algorithm).digest()


def context():
    manifest = Path(os.environ["SIMIT_NATIVE_MANIFEST"])
    require(not manifest.is_absolute() and ".." not in manifest.parts, "invalid manifest path")
    namespace = os.environ["SIMIT_NATIVE_NAMESPACE"]
    registry = os.environ["SIMIT_NATIVE_REGISTRY"]
    require(registry in ("python", "npm"), "unsupported native registry")
    package = os.environ["SIMIT_NATIVE_PACKAGE"]
    tag = os.environ["GITHUB_REF_NAME"]
    require(tag.startswith(namespace + "/v"), "unexpected release namespace")
    version = tag.removeprefix(namespace + "/v")
    source = subprocess.check_output(["git", "rev-parse", "HEAD"], text=True).strip()
    tagged = subprocess.check_output(["git", "rev-list", "-n", "1", "refs/tags/" + tag], text=True).strip()
    require(source == tagged == os.environ["GITHUB_SHA"], "release source differs from signed tag/event")
    data = tomllib.loads(manifest.read_text())["project"] if registry == "python" else json.loads(manifest.read_text())
    require(data["name"] == package and data["version"] == version, "tagged manifest identity/version mismatch")
    require(not data.get("private", False), "private packages cannot be published")
    if registry == "npm":
        require("+" not in version, "public native releases cannot have SemVer build metadata")
        config = data.get("publishConfig", {})
        require(config.get("registry", "https://registry.npmjs.org/").rstrip("/") == "https://registry.npmjs.org", "custom npm registry requires its own publication backend")
        require(not ("tag" not in config and "-" in version), "npm prereleases require an explicit publishConfig.tag")
    native_version = python_version(version) if registry == "python" else version
    return manifest.parent.resolve(), (Path(os.environ["RUNNER_TEMP"]) / "native-release-dist").resolve(), {
        "schemaVersion": 1, "registry": registry, "name": package, "version": native_version,
        "namespace": namespace, "tag": tag, "source": source,
    }


def archive_identity(path, identity):
    if identity["registry"] == "npm":
        with tarfile.open(path, "r:gz") as archive:
            item = archive.getmember("package/package.json")
            require(item.isfile() and item.size <= 1024 * 1024, "invalid packed npm manifest")
            data = json.load(archive.extractfile(item))
            require(not data.get("private", False), "packed package is private")
            require(data.get("publishConfig", {}).get("registry", "https://registry.npmjs.org/").rstrip("/") == "https://registry.npmjs.org", "packed npm registry is not public npm")
            name, version = data["name"], data["version"]
    else:
        if path.suffix == ".whl":
            with zipfile.ZipFile(path) as archive:
                entries = [entry for entry in archive.infolist() if entry.filename.endswith(".dist-info/METADATA")]
                require(len(entries) == 1 and entries[0].file_size <= 1024 * 1024, "invalid wheel metadata")
                text = archive.read(entries[0]).decode()
        else:
            with tarfile.open(path, "r:gz") as archive:
                entries = [entry for entry in archive.getmembers() if entry.name.count("/") == 1 and entry.name.endswith("/PKG-INFO")]
                require(len(entries) == 1 and entries[0].isfile() and entries[0].size <= 1024 * 1024, "invalid sdist metadata")
                text = archive.extractfile(entries[0]).read().decode()
        data = email.parser.Parser().parsestr(text)
        name, version = data["Name"], data["Version"]
    require((normalize(name) == normalize(identity["name"]) if identity["registry"] == "python" else name == identity["name"]) and version == identity["version"], "artifact identity/version differs from tagged manifest")


def inventory(paths, identity):
    require(paths and all(path.is_file() and not path.is_symlink() for path in paths), "native build produced invalid artifacts")
    suffixes = (".whl", ".tar.gz") if identity["registry"] == "python" else (".tgz",)
    require(len(paths) == len(suffixes) and all(sum(path.name.endswith(suffix) for path in paths) == 1 for suffix in suffixes), "native release requires one wheel and sdist or one npm tarball")


def pack(directory, out, identity):
    out.mkdir(parents=True, exist_ok=False)
    env = dict(os.environ, SOURCE_DATE_EPOCH=subprocess.check_output(["git", "log", "-1", "--format=%ct"], text=True).strip())
    # Pack/build never receives a registry publication credential.
    env.pop("NODE_AUTH_TOKEN", None)
    env.pop("UV_PUBLISH_TOKEN", None)
    if identity["registry"] == "python":
        command(["uv", "build", "--project", str(directory), "--out-dir", str(out)], env=env)
        ignore = out / ".gitignore"
        if ignore.exists():
            require(ignore.is_file() and not ignore.is_symlink() and ignore.read_text().strip() == "*", "unexpected uv output marker")
            ignore.unlink()
    else:
        command(["npm", "pack", "--ignore-scripts", "--json", "--pack-destination", str(out)], cwd=directory, env=env)
    paths = sorted(out.iterdir())
    inventory(paths, identity)
    for path in paths:
        archive_identity(path, identity)
    receipt = identity | {"files": {path.name: digest(path).hex() for path in paths}}
    (out / "receipt.json").write_text(json.dumps(receipt, sort_keys=True) + "\n")


def registry_metadata(identity):
    name = urllib.parse.quote(identity["name"], safe="")
    version = urllib.parse.quote(identity["version"], safe="")
    # https://docs.pypi.org/api/json/#get-a-release
    # https://github.com/npm/registry/blob/main/docs/responses/package-metadata.md
    url = f"https://pypi.org/pypi/{name}/{version}/json" if identity["registry"] == "python" else f"https://registry.npmjs.org/{name}"
    request = urllib.request.Request(url, headers={"Accept": "application/vnd.npm.install-v1+json, application/json", "User-Agent": "simit native release"})
    try:
        with urllib.request.urlopen(request, timeout=10) as response:
            data = response.read(4 * 1024 * 1024 + 1)
            require(len(data) <= 4 * 1024 * 1024, "native registry metadata exceeds 4 MiB")
            return json.loads(data)
    except urllib.error.HTTPError as error:
        if error.code == 404:
            return None
        raise


def missing_files(out, identity, files):
    metadata = registry_metadata(identity)
    if metadata is None:
        return list(files)
    if identity["registry"] == "npm":
        require(metadata["name"] == identity["name"], "npm registry package identity mismatch")
        release = metadata["versions"].get(identity["version"])
        if release is None:
            return list(files)
        require(release["name"] == identity["name"] and release["version"] == identity["version"], "npm registry release identity mismatch")
        name = next(iter(files))
        integrity = "sha512-" + base64.b64encode(digest(out / name, "sha512")).decode()
        require(release["dist"]["integrity"] == integrity, "npm registry checksum conflict")
        return []
    require(normalize(metadata["info"]["name"]) == normalize(identity["name"]) and metadata["info"]["version"] == identity["version"], "PyPI registry release identity mismatch")
    published = {item["filename"]: item for item in metadata["urls"]}
    for name, checksum in files.items():
        if name in published:
            require(not published[name]["yanked"] and published[name]["digests"]["sha256"] == checksum, "PyPI registry checksum conflict or yanked artifact")
    return [name for name in files if name not in published]


def publish(out, identity):
    receipt = json.loads((out / "receipt.json").read_text())
    files = receipt.pop("files")
    require(receipt == identity and files, "native artifact receipt differs from signed source")
    require(set(path.name for path in out.iterdir()) == set(files) | {"receipt.json"}, "native artifact inventory mismatch")
    for name, checksum in files.items():
        require(Path(name).name == name and name not in (".", ".."), "invalid artifact filename")
        path = out / name
        require(path.is_file() and not path.is_symlink() and digest(path).hex() == checksum, "native artifact checksum mismatch")
        archive_identity(path, identity)
    inventory([out / name for name in files], identity)
    pending = missing_files(out, identity, files)
    if not pending:
        print("Exact native release already propagated")
        return
    token = "UV_PUBLISH_TOKEN" if identity["registry"] == "python" else "NODE_AUTH_TOKEN"
    require(os.environ.get(token, "").strip(), f"missing {token}")
    with tempfile.TemporaryDirectory(prefix="simit-native-publish-") as temporary:
        env = dict(os.environ, HOME=temporary, XDG_CONFIG_HOME=temporary)
        paths = [str(out / name) for name in pending]
        if identity["registry"] == "python":
            args = ["uv", "--no-config", "publish", "--publish-url", "https://upload.pypi.org/legacy/", *paths]
        else:
            config = Path(temporary) / "npmrc"
            config.write_text("//registry.npmjs.org/:_authToken=${NODE_AUTH_TOKEN}\nregistry=https://registry.npmjs.org/\n")
            config.chmod(0o600)
            args = ["npm", "publish", "--ignore-scripts", "--userconfig", str(config), "--registry", "https://registry.npmjs.org/", *paths]
        result = subprocess.run(args, cwd=temporary, env=env)
    # A concurrent exact publication is accepted only after matching checksums.
    for attempt in range(20):
        if not missing_files(out, identity, files):
            print("Exact native release propagated with matching checksums")
            return
        require(result.returncode == 0, "native publication failed and exact artifacts are absent")
        if attempt < 19:
            time.sleep(30)
    raise RuntimeError("native registry propagation deadline exceeded")


def main():
    require(len(sys.argv) == 2 and sys.argv[1] in ("pack", "publish"), "expected pack or publish")
    directory, out, identity = context()
    if sys.argv[1] == "pack":
        pack(directory, out, identity)
    else:
        publish(out, identity)


if __name__ == "__main__":
    main()
