---
# yamllint disable rule:line-length
name: CI

"on":
  push:
    branches: [trunk]
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  check:
    runs-on: atlas
    steps:
      - uses: https://code.forgejo.org/actions/checkout@v4

      - uses: https://github.com/cachix/install-nix-action@v27
        with:
          extra_nix_config: |
            experimental-features = nix-command flakes
            substituters = https://attic.candee.baby/canix https://cache.nixos.org
            trusted-public-keys = canix:uqr0nD3I0mfj9BYfZgTZHMaDKfI2yCTtSA5JGTWKUeg= cache.nixos.org-1:6NCHdD59X431o0gWypbMrAURkbJ16ZPMQFGspcDShjY=

      - name: Flake check
        run: nix flake check --keep-going --print-build-logs

      - name: Push to Attic
        if: github.ref == 'refs/heads/trunk' || github.ref == 'refs/heads/main'
        run: |
          nix profile install nixpkgs#attic-client
          attic login canix https://attic.candee.baby "$(cat "$ATTIC_TOKENS_DIR/simit")"
          nix build --print-out-paths --no-link \
            .#checks.x86_64-linux.simit-deps \
            .#packages.x86_64-linux.default \
            | xargs attic push canix
