---
name: Publish Pages

"on":
  push:
    branches: [trunk]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  publish:
    runs-on: atlas
    container: nixos/nix:latest
    steps:
      - name: Checkout
        uses: https://code.forgejo.org/actions/checkout@v4

      - name: Build site
        run: nix --extra-experimental-features "nix-command flakes" build .#site

      - name: Publish to Codeberg Pages
        uses: https://codeberg.org/git-pages/action@v2
        with:
          site: "https://${{ forge.repository_owner }}.codeberg.page/simit/"
          token: ${{ forge.token }}
          source: result/
