use std::path::PathBuf;

use crate::project::{GeneratedFile, Languages};

/// Render simit's compact, language-aware project ignore file.
pub fn file(languages: &Languages) -> GeneratedFile {
    GeneratedFile {
        relative_path: PathBuf::from(".gitignore"),
        content: template(languages),
    }
}

pub fn template(languages: &Languages) -> String {
    let mut content = String::from(
        "# Generated by simit init gitignore.\n\n\
         # Operating-system and editor files\n\
         .DS_Store\n\
         Thumbs.db\n\
         *.swp\n\
         *.swo\n\
         .idea/\n\
         .vscode/\n\n\
         # Local configuration and credentials\n\
         .env\n\
         .env.*\n\
         !.env.example\n\
         !.env.template\n\
         .envrc\n\n\
         # Local tools and generated project metadata\n\
         .agents/\n\
         .claude/\n\
         .opencode/\n\
         .skills/\n\
         .cache/\n\
         .tmp/\n\
         .tmp*/\n\
         .pre-commit-config.yaml\n\
         *.log\n\
         logs/\n\n\
         # Nix and documentation outputs\n\
         .direnv/\n\
         result\n\
         result-*\n\
         docs/book/\n\n",
    );

    if languages.rust {
        content.push_str("# Rust\ntarget/\n\n");
    }

    if languages.uv_python {
        content.push_str(
            "# Python\n\
             __pycache__/\n\
             *.py[cod]\n\
             .venv/\n\
             venv/\n\
             .pytest_cache/\n\
             .mypy_cache/\n\
             .ruff_cache/\n\
             .ipynb_checkpoints/\n\
             .coverage\n\
             .coverage.*\n\
             htmlcov/\n\
             *.egg-info/\n\n",
        );
    }

    // These directories are generated by the common JavaScript toolchains and
    // are safe to ignore even when a project is otherwise language-agnostic.
    content.push_str(
        "# JavaScript and frontend build outputs\n\
         node_modules/\n\
         .next/\n\
         .turbo/\n\
         .vite/\n",
    );

    content
}

#[cfg(test)]
mod tests {
    use super::template;
    use crate::project::Languages;

    #[test]
    fn common_template_is_compact_and_deterministic() {
        let first = template(&Languages::default());
        let second = template(&Languages::default());

        assert_eq!(first, second);
        assert!(first.contains(".direnv/\n"));
        assert!(first.contains("node_modules/\n"));
        assert!(!first.contains("target/\n"));
        assert!(first.len() < 1_500);
    }

    #[test]
    fn language_sections_are_added_only_when_detected() {
        let content = template(&Languages {
            rust: true,
            uv_python: true,
            ..Languages::default()
        });

        assert!(content.contains("# Rust\ntarget/\n"));
        assert!(content.contains("# Python\n"));
        assert!(content.contains("__pycache__/\n"));
    }
}
