[book]
title = "simit Documentation"
authors = ["simit contributors"]
language = "en"
src = "src"

[build]
build-dir = "book"

[output.html]
site-url = "/simit/"
default-theme = "coal"
preferred-dark-theme = "coal"
git-repository-url = "https://github.com/caniko/simit"
